name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  schedule:
    # Run every day at 9 AM UTC to check for new updates
    - cron: '0 9 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      contents: write  # Needed to push changes back to repo
      actions: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Generate JSON data files
        run: |
          echo "Starting data generation..."
          npm run generate-data || {
            echo "Data generation failed, using fallback..."
            npm run generate-fallback
          }
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'

      - name: Verify data files were created
        run: |
          echo "Checking if data directory exists..."
          ls -la
          if [ -d "data" ]; then
            echo "Data directory found. Contents:"
            ls -la data/
            echo "Checking subdirectories..."
            if [ -d "data/updates" ]; then
              echo "Updates directory contents:"
              ls -la data/updates/
            fi
            if [ -d "data/notices" ]; then
              echo "Notices directory contents:"
              ls -la data/notices/
            fi
            echo "File sizes:"
            find data/ -type f -exec du -h {} \;
          else
            echo "Data directory not found! Creating fallback data..."
            mkdir -p data/updates data/notices
            npm run generate-fallback
            echo "Fallback data created:"
            find data/ -type f -exec ls -la {} \;
          fi

      - name: Data generation complete
        run: |
          echo "✅ Data files generated successfully during build"
          echo "📊 Generated files will be included in the static web app deployment"
          echo "🚫 No git commit needed - data files are now excluded from repository"

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_FIELD_08DC7E403 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "/" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_FIELD_08DC7E403 }}
          action: "close"
